### ISSUE TITLE
visitviewer dies when number of steps in a given SEQ  > 10

### ISSUE THREAD

**Issue by cnaw** [spacetelescope/jwst_visit_viewer#5]
Hi Marshall,
There is an incompatibility on how the numbering of visit files is sequenced and how visitviewer interprets them, Here is a case for CR-1625 NRC-17 APTID 1067 visits 451-454 where each visits is a mosaic of 2 x 10 positions[ https://outerspace.stsci.edu/download/attachments/135266807/V01067451001.vst?version=1&modificationDate=1648079901468&api=v2](url).  The visit files are generated following 08,09,0A,0B...,0Z, 10, 11, 12 . If visitviewer reads these values as strings, would it still be able to make the plots ?
[2208301f01_opgs_no_SBU.zip](https://github.com/spacetelescope/jwst_visit_viewer/files/8337517/2208301f01_opgs_no_SBU.zip)
By the way, this is a great tool!
Christopher

**Comment by mperrin** [comment]
Hi @cnaw, I finally had time to check back at this. I don't see an error right now running the current version of this tool on that visit file. 

I ran into this same issue and had fixed the parsing of the activity counters to be in base 36 back about a month ago, in commit 883435c . Is there a chance you may have been still using an earlier version of the code when you encounter this problem? 

Now, separately there's the issue that the code just plots a single pointing rather than all the mosaic tiles. But that's a lot more complex...

**Comment by cnaw** [comment]
Hi @mperrin ,
My bad - I was unaware there had been a fix. I have been using an older version (probably several months old). Thanks!
Plotting one pointing is already super-helpful - this allows estimating where the guide-star is bright enough or is at an edge, etc. A mosaic for the different pointings (and the different slews until guiding starts)  would be great, but I also think it would require a lot of effort for only a modest  gain.

**Comment by mperrin** [comment]
Actually it turns out it was only modest effort to get some mosaic display working!   I had a version of that code already from the OTE-01 mosaic display (which was a larger effort last fall, yes), and I was able to generalize that. I just pushed that commit along with some other improvements, so grab the latest and make sure you have up through commit 250b026

<img width="1150" alt="Screen Shot 2022-04-01 at 12 09 22 PM" src="https://user-images.githubusercontent.com/1151745/161301453-39861271-6df2-45f0-87bd-4235a6a36522.png">

**Comment by mperrin** [comment]
@cnaw and yes if you've been using a several months old version you will see a lot of improvements. The display of guiding information was substantially overhauled and enhanced during the course of all the work that went into tuning up observatory LOS performance
